services:
  nginx:
    image: nginx:1.27-alpine
    expose:
      - "80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../certs:/etc/nginx/certs
    depends_on:
      - beta-backend
      - beta-frontend
  beta-backend:
    image: juliusse/ssponline-backend:${IMAGE_TAG:-latest}
    deploy:
      resources:
        limits:
          memory: 2000M
    expose:
      - "8081"

  beta-frontend:
    image: juliusse/ssponline-frontend:${IMAGE_TAG:-latest}
    expose:
      - "8080"
    env_file:
      - ./frontend.env
    depends_on:
      - beta-backend
