version: "3"

services:
  nginx:
    image: juliusse/ssponline-nginx:${IMAGE_TAG:-latest}
    expose:
      - "80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../certs:/etc/nginx/certs
    depends_on:
      - beta-backend
      - beta-frontend
  beta-backend:
    image: juliusse/ssponline-backend:${IMAGE_TAG:-latest}
    deploy:
      resources:
        limits:
          memory: 2000M
    expose:
      - "8081"

  beta-frontend:
    image: juliusse/ssponline-frontend:${IMAGE_TAG:-latest}
    expose:
      - "5000"
    volumes:
      - ./beta.frontend.config.js:/app/build/config.js
    depends_on:
      - beta-backend
