export enum GameActionType {
    CONFIGURE = "CONFIGURE",
    SHUFFLE_UNITS = "SHUFFLE_UNITS",
    ACCEPT_UNITS = "ACCEPT_UNITS",
    SET_SPECIAL_UNITS = "SET_SPECIAL_UNITS",
    START = "START",
    MOVE = "MOVE",
    FIGHT = "FIGHT",
    FIGHT_CHOOSE_UNIT = "FIGHT_CHOOSE_UNIT"
}
