# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew backend:test
  test-fe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: cd frontend && npm i && CI=true npm test

  package-be:
    needs: [ test-be ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Image
        run: ./gradlew backend:bootBuildImage
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Retag image for commit
        run: docker tag docker.pkg.github.com/juliusse/ssponline/backend:latest docker.pkg.github.com/juliusse/ssponline/backend:$GITHUB_SHA
      - name: Push the image
        run: docker push docker.pkg.github.com/juliusse/ssponline/backend:$GITHUB_SHA

  package-fe:
    needs: [ test-fe ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Builds image
        run: docker build --build-arg APP_URL="http://beta.ssponline.de:8081" --tag docker.pkg.github.com/juliusse/ssponline/frontend:latest ./frontend
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Retag image for commit
        run: docker tag docker.pkg.github.com/juliusse/ssponline/frontend:latest docker.pkg.github.com/juliusse/ssponline/frontend:$GITHUB_SHA
      - name: Push the image
        run: docker push docker.pkg.github.com/juliusse/ssponline/frontend:$GITHUB_SHA

  deploy:
    needs: [ package-be, package-fe ]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: pull be image for commit
        run: docker pull docker.pkg.github.com/juliusse/ssponline/backend:$GITHUB_SHA
      - name: Retag be image to latest
        run: docker tag docker.pkg.github.com/juliusse/ssponline/backend:$GITHUB_SHA docker.pkg.github.com/juliusse/ssponline/backend:latest
      - name: Push be image
        run: docker push docker.pkg.github.com/juliusse/ssponline/backend:latest
      - name: pull fe image for commit
        run: docker pull docker.pkg.github.com/juliusse/ssponline/frontend:$GITHUB_SHA
      - name: Retag fe image to latest
        run: docker tag docker.pkg.github.com/juliusse/ssponline/frontend:$GITHUB_SHA docker.pkg.github.com/juliusse/ssponline/frontend:latest
      - name: Push fe image
        run: docker push docker.pkg.github.com/juliusse/ssponline/frontend:latest
      - name: Add ssh key
        run: echo "${{ secrets.AWS_SSH_KEY}}" >> ~/ssh_key && chmod 600 ~/ssh_key
      - name: Update be Deployment
        run: ssh -o StrictHostKeyChecking=no -i ~/ssh_key ec2-user@18.156.4.123 "docker pull docker.pkg.github.com/juliusse/ssponline/backend:latest; docker stop ssponline_backend; docker rm ssponline_backend; docker run -d -p 8081:8081 -m 2000000000 --name ssponline_backend -d docker.pkg.github.com/juliusse/ssponline/backend:latest"
      - name: Update fe Deployment
        run: ssh -o StrictHostKeyChecking=no -i ~/ssh_key ec2-user@18.156.4.123 "docker pull docker.pkg.github.com/juliusse/ssponline/frontend:latest; docker stop ssponline_frontend; docker rm ssponline_frontend; docker run -d -p 80:5000 -m 1000000000 --name ssponline_frontend -d docker.pkg.github.com/juliusse/ssponline/frontend:latest"
