# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Frontend Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Builds image
        run: docker build --build-arg APP_URL="http://beta.ssponline.de:8081" --tag docker.pkg.github.com/juliusse/ssponline/frontend:latest ./frontend
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push the image
        run: docker push docker.pkg.github.com/juliusse/ssponline/frontend:latest
      - name: Add ssh key
        run: echo "${{ secrets.AWS_SSH_KEY}}" >> ~/ssh_key && chmod 600 ~/ssh_key
      - name: Update Deployment
        run: ssh -o StrictHostKeyChecking=no -i ~/ssh_key ec2-user@18.156.4.123 "docker pull docker.pkg.github.com/juliusse/ssponline/frontend:latest; docker stop ssponline_frontend; docker rm ssponline_frontend; docker run -d -p 80:5000 -m 1000000000 --name ssponline_frontend -d docker.pkg.github.com/juliusse/ssponline/frontend:latest"
